### ISSUE TITLE
Internal Server Error (The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.)

### ISSUE THREAD

**Issue by MahdeenSky** [Recentaly/DeepInfra-Wrapper#1]
Get models work
```json
{
  "data": [
    {
      "id": "codellama/CodeLlama-70b-Instruct-hf"
    },
    {
      "id": "codellama/CodeLlama-34b-Instruct-hf"
    },
    {
      "id": "jondurbin/airoboros-l2-70b-gpt4-1.4.1"
    },
    {
      "id": "mistralai/Mistral-7B-Instruct-v0.1"
    },
    {
      "id": "mistralai/Mixtral-8x7B-Instruct-v0.1"
    },
    {
      "id": "cognitivecomputations/dolphin-2.6-mixtral-8x7b"
    },
    {
      "id": "lizpreciatior/lzlv_70b_fp16_hf"
    },
    {
      "id": "deepinfra/airoboros-70b"
    }
  ]
}
```
but the following error occurs when i try to use the api 
```python
    data = {
        "messages": [{"role": "user", "content": "Hello, World!"}],
        "model": "mistralai/Mixtral-8x7B-Instruct-v0.1",
        "max_tokens": 150,
        "top_p": 1
    }
```

Sending a post request, gives this error.
```html
<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

This is the error in the API
```
2024-04-06 05:04:18,440 Exception on /chat/completions [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/content/DeepInfra-Wrapper/app.py", line 73, in chat
    api.config["max_tokens"] = max_tokens
AttributeError: 'Api' object has no attribute 'config'
2024-04-06 05:04:18,442 127.0.0.1 - - [06/Apr/2024 05:04:18] "POST /chat/completions HTTP/1.1" 500 -
2024-04-06 05:04:18,449 Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/content/DeepInfra-Wrapper/app.py", line 73, in chat
    api.config["max_tokens"] = max_tokens
AttributeError: 'Api' object has no attribute 'config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/serving.py", line 323, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1727, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
TypeError: internal_server_error() takes 0 positional arguments but 1 was given
```

**Comment by Recentaly** [comment]
Fixed. Apologies for not seeing this earlier.
